/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFiles;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pratap
 */
public class addtocart extends javax.swing.JFrame {

    /**
     * Creates new form addtocart
     */
    // === DB settings (use ONE schema consistently) ===
private static final String DB_URL = "jdbc:mysql://localhost:3306/java_stock?useSSL=false&serverTimezone=UTC";
private static final String DB_USER = "root";
private static final String DB_PASS = "root"; // <-- keep consistent

    String roll;
    public addtocart() {
        initComponents();
        roll="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "item_id", "item_name", "quantity", "unit price", "total price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table2.setRowHeight(25);
        table2.setRowMargin(3);
        jScrollPane1.setViewportView(table2);
        if (table2.getColumnModel().getColumnCount() > 0) {
            table2.getColumnModel().getColumn(1).setMinWidth(140);
        }

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton1.setText("View Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Total Amount");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("Proceed to bill");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1003, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        
        DefaultTableModel model = (DefaultTableModel) table2.getModel();
    model.setRowCount(0);

    // Always compute line total = qty * unit price locally to avoid bad/empty totprice in DB
    java.math.BigDecimal grandTotal = java.math.BigDecimal.ZERO;

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        try (Connection con = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS);
             Statement stmt = con.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT item_id, item_name, quantity, price, totprice FROM cart")) {

            while (rs.next()) {
                String id = rs.getString("item_id");
                String name = rs.getString("item_name");

                int qty = 0;
                try { qty = Integer.parseInt(String.valueOf(rs.getObject("quantity"))); } catch (Exception ignore) {}

                java.math.BigDecimal unitPrice = java.math.BigDecimal.ZERO;
                try { unitPrice = new java.math.BigDecimal(String.valueOf(rs.getObject("price"))); } catch (Exception ignore) {}

                // compute line total even if DB has a stale/missing totprice
                java.math.BigDecimal lineTotal = unitPrice.multiply(java.math.BigDecimal.valueOf(qty));

                model.addRow(new Object[]{ id, name, qty, unitPrice, lineTotal });

                grandTotal = grandTotal.add(lineTotal);
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading cart: " + e.getMessage());
    }

    jLabel2.setText(grandTotal.toPlainString()); // show final total
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setVisible(false);
        Searchproduct mm=new Searchproduct();
        mm.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        // Pass the currently visible cart rows to bill.java
    javax.swing.table.DefaultTableModel cartModel =
            (javax.swing.table.DefaultTableModel) table2.getModel();

    // If table is empty, remind the user to load the cart first
    if (cartModel.getRowCount() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Cart is empty. Click 'View Cart' first.");
        return;
    }

    // Open bill screen with cart data (no DB writes yet)
    this.setVisible(false);
    bill b = new bill(cartModel);
    b.setVisible(true);
//       DefaultTableModel model = (DefaultTableModel) table2.getModel();
//    int rowCount = model.getRowCount();
//
//    if (rowCount == 0) {
//        JOptionPane.showMessageDialog(this, "Cart is empty. Click 'View Cart' first.");
//        return;
//    }
//
//    try {
//        Class.forName("com.mysql.cj.jdbc.Driver");
//        try (Connection con = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS)) {
//            con.setAutoCommit(false);
//
//            // 1) Insert all cart rows into bill (use PreparedStatement to avoid SQL injection/type issues)
//            try (java.sql.PreparedStatement psInsert =
//                         con.prepareStatement("INSERT INTO bill(item_id,item_name,quantity,price,totprice) VALUES(?,?,?,?,?)");
//                 java.sql.PreparedStatement psGetQty =
//                         con.prepareStatement("SELECT quantity FROM inventory WHERE item_id=?");
//                 java.sql.PreparedStatement psUpdInv =
//                         con.prepareStatement("UPDATE inventory SET quantity=? WHERE item_id=?");
//                 Statement stmt = con.createStatement()) {
//
//                for (int r = 0; r < rowCount; r++) {
//                    String itemId = String.valueOf(model.getValueAt(r, 0));
//                    String itemName = String.valueOf(model.getValueAt(r, 1));
//
//                    int qty = 0;
//                    try { qty = Integer.parseInt(String.valueOf(model.getValueAt(r, 2))); } catch (Exception ignore) {}
//
//                    java.math.BigDecimal unitPrice = java.math.BigDecimal.ZERO;
//                    try { unitPrice = new java.math.BigDecimal(String.valueOf(model.getValueAt(r, 3))); } catch (Exception ignore) {}
//
//                    java.math.BigDecimal lineTotal = unitPrice.multiply(java.math.BigDecimal.valueOf(qty));
//
//                    // Insert into bill
//                    psInsert.setString(1, itemId);
//                    psInsert.setString(2, itemName);
//                    psInsert.setInt(3, qty);
//                    psInsert.setBigDecimal(4, unitPrice);
//                    psInsert.setBigDecimal(5, lineTotal);
//                    psInsert.executeUpdate();
//
//                    // 2) Update inventory = inventory.quantity - qty
//                    psGetQty.setString(1, itemId);
//                    try (ResultSet rs = psGetQty.executeQuery()) {
//                        if (rs.next()) {
//                            int current = 0;
//                            try { current = Integer.parseInt(String.valueOf(rs.getObject(1))); } catch (Exception ignore) {}
//                            int updated = Math.max(0, current - qty);
//                            psUpdInv.setInt(1, updated);
//                            psUpdInv.setString(2, itemId);
//                            psUpdInv.executeUpdate();
//                        }
//                    }
//                }
//
//                // 3) Clear cart (same schema!)
//                stmt.executeUpdate("DELETE FROM cart");
//            }
//
//            con.commit();
//            JOptionPane.showMessageDialog(this, "Items moved to bill and inventory updated.");
//        }
//    } catch (Exception e) {
//        JOptionPane.showMessageDialog(this, "Billing failed: " + e.getMessage());
//        return;
//    }
//
//    // Show bill screen
//    this.setVisible(false);
//    bill mm = new bill();
//    mm.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addtocart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addtocart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addtocart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addtocart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addtocart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables
}
